# Configura o caminho do banco de dados (será criado um arquivo chamado wheels.db na raiz do projeto)
spring.datasource.url=jdbc:sqlite:wheels.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Diz ao Hibernate para criar as tabelas no banco de dados automaticamente com base nas nossas classes Java
spring.jpa.hibernate.ddl-auto=update

# Configura o dialeto específico do SQLite para conversão de comandos
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Mostra no console do IntelliJ os comandos de banco que estão acontecendo nos bastidores (ótimo para depurar)
spring.jpa.show-sql=true